version: '3'
services:
 docker-app:
    image: emmanuelneri/spring-boot-docker-app
    ports:
      - "8080:8080"
    depends_on:
      - docker-postgres
 docker-postgres:
    image: postgres:10.4
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
